# Data Handling & Visualization 1 — Tabular data, Excel, and CSV

**Digital Foundation for Chemical Engineers**  \nDuration: 60 minutes

## Today’s goal
Recognise tidy process data, understand the roles of Excel and CSV files, and start working with tables in Python. We will use the `pandas` library, a widely used tool for tabular data.

## 1. Why data management matters (10 min)

A plant may record thousands of sensor values, laboratory results, and batch records. Useful analysis depends on data being understandable and traceable.

### A tidy-table habit
- One **row** = one observation (for example, one hourly reading).
- One **column** = one variable (for example, temperature in °C).
- One **cell** = one value.
- Give columns meaningful names including units: `flow_m3_h`, not `Flow1`.

Excel is convenient for manual inspection; **CSV** is a plain-text table format that moves easily between Excel, Python, and reporting tools.

## 2. DataFrames: tables in Python (12 min)

A pandas **DataFrame** is like a spreadsheet table in Python. It has named columns and numbered rows. Run this cell; the first execution may take a moment while the library loads.

If `pandas` is unavailable in a new Codespace, run `pip install pandas` in the terminal, then restart the kernel.

In [1]:
import pandas as pd

process_data = pd.DataFrame({
    'hour': [8, 9, 10, 11, 12],
    'temperature_c': [72.1, 73.5, 75.2, 74.8, 76.0],
    'pressure_bar': [4.8, 4.9, 5.1, 5.0, 5.2],
    'flow_m3_h': [12.0, 12.3, 11.9, 12.1, 12.4]
})
process_data

   hour  temperature_c  pressure_bar  flow_m3_h
0     8           72.1           4.8       12.0
1     9           73.5           4.9       12.3
2    10           75.2           5.1       11.9
3    11           74.8           5.0       12.1
4    12           76.0           5.2       12.4

**Run and modify (4 min):** Change a temperature value, rerun the cell, and observe the changed table. Add a `ph` column with five values.

**Challenge:** Create a second DataFrame for three batches with columns `batch_id`, `mass_kg`, and `yield_percent`.

In [3]:
import pandas as pd

process_data = pd.DataFrame({
    'hour': [8, 9, 10, 11, 12],
    'temperature_c': [72.1, 73.5, 75.2, 74.8, 76.0],
    'pressure_bar': [4.8, 4.9, 5.1, 5.0, 5.2],
    'flow_m3_h': [12.0, 12.3, 11.9, 12.1, 12.4],
    'ph': [6.8, 6.9, 7.1, 7.0, 7.2]
})
process_data

   hour  temperature_c  pressure_bar  flow_m3_h   ph
0     8           72.1           4.8       12.0  6.8
1     9           73.5           4.9       12.3  6.9
2    10           75.2           5.1       11.9  7.1
3    11           74.8           5.0       12.1  7.0
4    12           76.0           5.2       12.4  7.2

## 3. Inspect before analysing (15 min)

Never jump directly to a conclusion from a new file. First inspect its size, column names, data types, and a few rows. `head()` gives the first rows; `info()` describes columns; `describe()` gives numerical summaries.

In [13]:
print('Shape (rows, columns):', process_data.shape)
print('\nColumn names:', list(process_data.columns))
display(process_data.head())
process_data.info()
display(process_data.describe())

Shape (rows, columns): (5, 6)

Column names: ['time_h', 'inlet_temperature_C', 'outlet_temperature_C', 'flow_m3_h', 'status_note', 'delta_t_c']

,time_h,inlet_temperature_C,outlet_temperature_C,flow_m3_h,status_note,delta_t_c
0,8,72.1,74.0,12.0,0.1,12.1
1,9,73.5,79.5,12.3,0.2,13.5
2,10,75.2,80.2,11.9,0.3,15.2
3,11,74.8,85.8,12.1,0.4,14.8
4,12,76.0,89.0,12.4,0.5,16.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time_h                5 non-null      int64
 1   inlet_temperature_C   5 non-null      float64
 2   outlet_temperature_C  5 non-null      float64
 3   flow_m3_h             5 non-null      float64
 4   status_note           5 non-null      float64
 5   delta_t_c             5 non-null      float64
dtypes: float64(5), int64(1)
memory usage: 372.0 bytes

,time_h,inlet_temperature_C,outlet_temperature_C,flow_m3_h,status_note,delta_t_c
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,10.000000,74.320000,81.700000,12.140000,0.300000,14.320000
std,1.581139,1.535252,5.841233,0.207364,0.158114,1.535252
min,8.000000,72.100000,74.000000,11.900000,0.100000,12.100000
25%,9.000000,73.500000,79.500000,12.000000,0.200000,13.500000
50%,10.000000,74.800000,80.200000,12.100000,0.300000,14.800000
75%,11.000000,75.200000,85.800000,12.300000,0.400000,15.200000
max,12.000000,76.000000,89.000000,12.400000,0.500000,16.000000

**Try it (5 min):** Answer from the output: How many readings are present? Which column has the highest average? Are all columns numerical?

**Challenge:** Use `process_data['temperature_c'].mean()` to calculate the mean directly, then format it to two decimals.

## 4. Excel and CSV: practical workflow (10 min)

A recommended workflow for this course:

1. Collect or export a controlled data table from a spreadsheet/system.
2. Save a working copy as **CSV UTF-8** with a clear file name and units in headers.
3. Import to Python, inspect it, clean it, then create repeatable outputs.
4. Keep the raw source unchanged; save cleaned data separately.

Avoid merged cells, decorative title rows, and mixed units in a single numeric column: they make reliable analysis harder.

## Pair task: design a data table (10 min)

You are recording hourly data from a heat exchanger. Propose five column names for time, inlet/outlet temperatures, flow, and a status note. Include units in appropriate names.

Then add a `delta_t_c` column below.

**Challenge:** Explain why storing `72 °C` as text is less useful than storing `72` in `temperature_c`.

In [12]:
process_data = pd.DataFrame({
    'time_h': [8, 9, 10, 11, 12],
    'inlet_temperature_C': [72.1, 73.5, 75.2, 74.8, 76.0],
    'outlet_temperature_C': [74, 79.5, 80.2, 85.8, 89.0],
    'flow_m3_h': [12.0, 12.3, 11.9, 12.1, 12.4],
    'status_note': [0.1,0.2,0.3,0.4,0.5],
})
process_data['delta_t_c'] = process_data['inlet_temperature_C'] - 60
process_data

,time_h,inlet_temperature_C,outlet_temperature_C,flow_m3_h,status_note,delta_t_c
0,8,72.1,74.0,12.0,0.1,12.1
1,9,73.5,79.5,12.3,0.2,13.5
2,10,75.2,80.2,11.9,0.3,15.2
3,11,74.8,85.8,12.1,0.4,14.8
4,12,76.0,89.0,12.4,0.5,16.0

## Exit check

You can distinguish Excel from CSV, explain tidy rows and columns, construct a DataFrame, and inspect a new table before trusting it. Next hour: import and export real CSV files.